# Dockerfile

FROM ruby:4.0.3

RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      libpq-dev \
      nodejs \
      npm \
      postgresql-client

WORKDIR /rails

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

COPY docker-entrypoint.sh /usr/bin/docker-entrypoint

RUN chmod +x /usr/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]

CMD ["bin/rails", "server", "-b", "0.0.0.0"]